---
name: "build-image"

"on":
  push:
    branches:
      - "main"
      - "testing-actions"
    paths:
      - "nix/**"
      - "package/**"
      - "justfile"
      - ".github/workflows/**"
  workflow_dispatch: {}

permissions:
  contents: "read"
  packages: "write"

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    container:
      image: "cgr.dev/chainguard/wolfi-base@sha256:80acfa73fe895c911f4c4d9a69f3767f61e345bc8ac896c05ae2ea832c0d2754" # yamllint disable-line rule:line-length
    env:
      NIX_CONFIG: "sandbox = false"
    steps:
      - name: "Install runner dependencies"
        run: "apk add --no-cache git bash curl skopeo xz libstdc++"

      - name: "Checkout"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"

      - name: "Install Nix"
        uses: "DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25" # yamllint disable-line rule:line-length

      - name: "Enable magic-nix-cache"
        uses: "DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d" # yamllint disable-line rule:line-length

      - name: "Build OCI image"
        run: |
          nix build \
            ./nix#caligaConfigurations.x86_64-linux.edge.config.build.image
          ./result > /tmp/image.tar

      - name: "Push to ghcr.io"
        env:
          GHCR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GHCR_USER: "${{ github.actor }}"
        run: |
          skopeo copy --dest-creds "$GHCR_USER:$GHCR_TOKEN" \
            docker-archive:/tmp/image.tar \
            docker://ghcr.io/wormt/edge:latest
